channels:
    - defaults

dependencies:
    - python=3.6
    - numpy
    - scipy
    - matplotlib
    - pandas
    - requests
    - h5py
    - sqlalchemy
    - configparser
    - tornado
    - pyqt
    - tensorflow>=2.2
    - tensorboard
    - tensorflow-probability
